#!/usr/bin/python

"""Amulet tests on a basic ceilometer deployment on trusty-icehouse."""

from basic_deployment import CeiloAgentBasicDeployment

if __name__ == '__main__':
    deployment = CeiloAgentBasicDeployment(series='trusty')
    deployment.run_tests()
