#!/usr/bin/python

"""Amulet tests on a basic ceilometer-agent deployment on trusty-juno."""

from basic_deployment import CeiloAgentBasicDeployment

if __name__ == '__main__':
    deployment = CeiloAgentBasicDeployment(series='trusty',
                                           openstack='cloud:trusty-juno',
                                           source='cloud:trusty-updates/juno')
    deployment.run_tests()
