#!/usr/bin/python

"""Amulet tests on a basic ceilometer-agent deployment on trusty-kilo."""

from basic_deployment import CeiloAgentBasicDeployment

if __name__ == '__main__':
    deployment = CeiloAgentBasicDeployment(series='trusty',
                                           openstack='cloud:trusty-kilo',
                                           source='cloud:trusty-updates/kilo')
    deployment.run_tests()
