#!/usr/bin/python

"""Amulet tests on a basic ceilometer-agent deployment on utopic-juno."""

from basic_deployment import CeiloAgentBasicDeployment

if __name__ == '__main__':
    deployment = CeiloAgentBasicDeployment(series='utopic')
    deployment.run_tests()
