#!/usr/bin/python

"""Amulet tests on a basic ceilometer-agent deployment on trusty-mitaka."""

from basic_deployment import CeiloAgentBasicDeployment

if __name__ == '__main__':
    deployment = CeiloAgentBasicDeployment(series='trusty',
                                           openstack='cloud:trusty-mitaka',
                                           source='cloud:trusty-updates/mitaka')
    deployment.run_tests()
