#!/usr/bin/python

"""Amulet tests on a basic ceilometer deployment on vivid-kilo."""

from basic_deployment import CeiloAgentBasicDeployment

if __name__ == '__main__':
    deployment = CeiloAgentBasicDeployment(series='vivid')
    deployment.run_tests()
