#!/usr/bin/python

"""Amulet tests on a basic ceilometer-agent deployment on xenial-mitaka."""

from basic_deployment import CeiloAgentBasicDeployment

if __name__ == '__main__':
    deployment = CeiloAgentBasicDeployment(series='xenial')
    deployment.run_tests()
